### ISSUE TITLE
Detect further XC functionals

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad-parser-openmx#13]
After the #5 is done, we can also add support for further supported functionals: http://www.openmx-square.org/openmx_man3.9/node23.html

LDA: 'LDA_X' and 'LDA_C_PZ'
LSDA-CA: 'LDA_X' and 'LDA_C_PZ'
LSDA-PW: 'LDA_X' and 'LDA_C_PW'

LDA is the default when no scf.XCType is specified.

**Comment by Mdmorshadurrahman** [comment]
I understood that if scf.XCType is none then i will add LDA as XC functional. But when or for which condition should i add LSDA-CA and LSDA-PW?

**Comment by ondracka** [comment]
If the scf.XCType is LDA than the section_XC_functionals1.XC_functional_name = 'LDA_X' and section_XC_functionals2.XC_functional_name = 'LDA_C_PZ'

The same applies of scf.XCType is none and also for the LSDA-CA.
If it is LSDA-PW than section_XC_functionals2.XC_functional_name = LDA_C_PZ should be 'LDA_C_PW'

**Comment by ondracka** [comment]
Fixed with 28ed8bfbafb6218fd8f706dff17ac164f3c83fb2 and 07e6e1ada1d2b91702f1184814db279569772a23.
