### ISSUE TITLE
Parse the smearing method

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad-parser-openmx#14]
This should go into section_method. OpenMX only supports the Fermi smearing:
`section_method.smearing_kind = 'fermi'`
and 
`section_method.smearing_width` should contain the value of `scf.ElectronicTemperature`  or default 300K if `scf.ElectronicTemperature` is not detected (converted from Kelvins to Joules).

**Comment by Mdmorshadurrahman** [comment]
do i need to make test case for this too?

**Comment by ondracka** [comment]
The testcases in the pull request are OK, just test it also for the new C2H2 case, which has the non-default smearing value of 500K.

**Comment by Mdmorshadurrahman** [comment]
if i use this `method def K_to_J(value): return (value * units.joules).to_base_units().magnitude`
will it work for converting from kelvin to Joules or can i do the conversion manually?

**Comment by ondracka** [comment]
Yeah, it should work.

**Comment by ondracka** [comment]
Fixed now, the conversion to energy was actually a slightly more complicated, as E=kT, sorry for not realizing straight away.
