### ISSUE TITLE
Section method

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad-parser-openmx#5]
Most stuff from the input should go here, some should be easy:

- [x] create the method section
- [x] `electronic_structure_method` should be always DFT
- [x] `section_XC_functionals` should have `XC_functional_name` GGA_C_PBE and GGA_X_PBE when scf.XcType is GGA-PBE (this is the default functinal we add other later)
- [x] `number_of_spin_channels`  2 if scf.SpinPolarization is on, 1 otherwise

I'll extend this list when the easy ones are done.

**Comment by ondracka** [comment]
See here for the metainfo scheme:
https://nomad-lab.eu/prod/rae/gui/metainfo/EntryArchive/section_run/section_method

**Comment by Mdmorshadurrahman** [comment]
> Most stuff from the input should go here, some should be easy:
> 
> * [ ]  create the method section
> * [ ]  `electronic_structure_method` should be always DFT
> * [ ]  `section_XC_functionals` should have `XC_functional_name` GGA_C_PBE and GGA_X_PBE when scf.XcType is GGA-PBE (this is the default functinal we add other later)
> * [ ]  `number_of_spin_channels`  2 if scf.SpinPolarization is on, 1 otherwise
> 
> I'll extend this list when the easy ones are done.

on which *.py file should i do all those coding?

**Comment by ondracka** [comment]
Nope, metainfo.py only contains definitions of properties which we want to save but are not part of standard nomad archive schema. All of the mentioned keys are part of standard section_method: https://nomad-lab.eu/prod/rae/gui/metainfo/EntryArchive/section_run/section_method so all of this would go directly into the general scheme so we need to modify just the parser.py.

So you should add appropriate regex lines to the mainfile parser to find scf.XcType and scf.SpinPolarization type, than add section_method to section_run with m_create, and save all of the properties in the appropriate places.

**Comment by Mdmorshadurrahman** [comment]
Updated section_method except changing **XC_functional_name**. For now, I kept it as it was by default.
![image](https://user-images.githubusercontent.com/65698541/116840574-9ec51800-abd6-11eb-94f7-9607cc172932.png)
should i create pull request?

**Comment by ondracka** [comment]
This is now done, good job.
