### ISSUE TITLE
Add the program_basis_set_type

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad-parser-openmx#6]
section_run/program_basis_set_type should be always "Numeric AOs"

**Comment by Mdmorshadurrahman** [comment]
can you provide me few hints or more details about this issue?

**Comment by ondracka** [comment]
Yeah, just add line
run.program_basis_set_type = "Numeric AOs"
somewhere. As this is always the case, there doesn't need to be any matching/parsing done (this is the only basis set type OpenMX supports).

Also add simple tests:
assert run.program_basis_set_type == 'Numeric AOs'
to both the test cases.
